CREATE TABLE tickets (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    order_id VARCHAR(10) NOT NULL,
    ticket_type VARCHAR(100) NOT NULL,
    quantity INT(11) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    fees DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
